comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  require_changes: true
  after_n_builds: 1

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

github_checks:
  annotations: false
