"""Type stubs for the murk Python module."""

class Vault:
    def get(self, key: str) -> str | None: ...
    def export(self) -> dict[str, str]: ...
    def keys(self) -> list[str]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: str) -> str: ...
    def __contains__(self, key: str) -> bool: ...
    def __repr__(self) -> str: ...

def load(vault_path: str = ".murk") -> Vault: ...
def get(key: str, vault_path: str = ".murk") -> str | None: ...
def export_all(vault_path: str = ".murk") -> dict[str, str]: ...
def has_key() -> bool: ...
