/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A loaded and decrypted murk vault. */
export declare class Vault {
  /**
   * Get a single decrypted secret value.
   * Returns the scoped override if one exists, otherwise the shared value.
   */
  get(key: string): string | null
  /** Export all secrets as an object. Scoped values override shared values. */
  export(): Record<string, string>
  /** List all key names. */
  keys(): Array<string>
  /** Number of secrets in the vault. */
  get length(): number
  /** Check if a key exists. */
  has(key: string): boolean
}

/** One-liner: load the vault and export all secrets as an object. */
export declare function exportAll(vaultPath?: string | undefined | null): Record<string, string>

/** One-liner: load the vault and get a single key. */
export declare function get(key: string, vaultPath?: string | undefined | null): string | null

/** Check if a MURK_KEY is available in the environment. */
export declare function hasKey(): boolean

/** Load a murk vault. Reads MURK_KEY from the environment. */
export declare function load(vaultPath?: string | undefined | null): Vault
