/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A loaded and decrypted murk vault. */
export declare class Vault {
  /**
   * Get a single decrypted secret value.
   * Returns the scoped override if one exists, otherwise the shared value.
   *
   * Internally, vault state stores values in `Zeroizing<String>` so plaintext
   * is wiped from memory when dropped. Crossing the napi boundary into a
   * JavaScript `String` requires copying the plaintext into a regular Rust
   * `String`; the V8 garbage collector owns it from there and zeroize cannot
   * follow. This is a known leak in the JS bindings — see THREAT_MODEL.md.
   */
  get(key: string): string | null
  /**
   * Export all secrets as an object. Scoped values override shared values.
   *
   * See `get` for the zeroize caveat — the returned `HashMap` holds plain
   * `String` plaintext, not `Zeroizing<String>`.
   */
  export(): Record<string, string>
  /** List all key names. */
  keys(): Array<string>
  /** Number of secrets in the vault. */
  get length(): number
  /** Check if a key exists. */
  has(key: string): boolean
}

/** One-liner: load the vault and export all secrets as an object. */
export declare function exportAll(vaultPath?: string | undefined | null): Record<string, string>

/** One-liner: load the vault and get a single key. */
export declare function get(key: string, vaultPath?: string | undefined | null): string | null

/** Check if a MURK_KEY is available in the environment. */
export declare function hasKey(): boolean

/** Load a murk vault. Reads MURK_KEY from the environment. */
export declare function load(vaultPath?: string | undefined | null): Vault
