/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A loaded and decrypted murk vault. */
export declare class Vault {
  /**
   * Get a single decrypted secret value. Resolution order: a personal scoped
   * override, then a named-group value we can read, then the shared value.
   *
   * Internally, vault state stores values in `Zeroizing<String>` so plaintext
   * is wiped from memory when dropped. Crossing the napi boundary into a
   * JavaScript `String` requires copying the plaintext into a regular Rust
   * `String`; the V8 garbage collector owns it from there and zeroize cannot
   * follow. This is a known leak in the JS bindings — see THREAT_MODEL.md.
   *
   * When the loaded identity is a granted agent, the vault's agent policy is
   * enforced before the value is returned — the same gate the CLI applies at
   * `agent exec`. Throws if policy forbids the key. For an operator identity
   * this is a no-op.
   */
  get(key: string): string | null
  /**
   * Export all secrets as an object. Scoped values override shared values.
   *
   * See `get` for the zeroize caveat — the returned `HashMap` holds plain
   * `String` plaintext, not `Zeroizing<String>`.
   *
   * For a granted agent, the vault's agent policy is enforced over the full
   * key set first (mirroring `murk agent exec`): if any resolvable key is
   * outside the policy, the whole export throws rather than returning a
   * partial object. For an operator identity this is a no-op.
   */
  export(): Record<string, string>
  /** List all key names. */
  keys(): Array<string>
  /** Number of secrets in the vault. */
  get length(): number
  /** Check if a key exists. */
  has(key: string): boolean
}

/** One-liner: load the vault and export all secrets as an object. */
export declare function exportAll(vaultPath?: string | undefined | null): Record<string, string>

/** One-liner: load the vault and get a single key. */
export declare function get(key: string, vaultPath?: string | undefined | null): string | null

/**
 * Whether a decryption identity (`MURK_KEY` / `MURK_KEY_FILE`) is available in
 * the environment — i.e. whether `load` can decrypt. This does not check
 * whether a secret exists; use `Vault.has` / `Vault.keys` for that.
 */
export declare function hasIdentity(): boolean

/** Load a murk vault. Reads MURK_KEY from the environment. */
export declare function load(vaultPath?: string | undefined | null): Vault
