.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH recover 1  "recover " 
.SH NAME
recover \- Re\-derive recovery phrase from current MURK_KEY
.SH SYNOPSIS
\fBmurk recover\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Re\-derive recovery phrase from current MURK_KEY
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
