.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ls 1  "ls " 
.SH NAME
ls \- List active agent grants and their TTLs
.SH SYNOPSIS
\fBmurk agent ls\fR [\fB\-\-json\fR] [\fB\-\-vault\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List active agent grants and their TTLs
.SH OPTIONS
.TP
\fB\-\-json\fR
Output as JSON
.TP
\fB\-\-vault\fR \fI<VAULT>\fR [default: .murk]
Vault filename
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
