.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH verify 1  "verify " 
.SH NAME
verify \- Verify vault integrity without exporting secrets
.SH SYNOPSIS
\fBmurk verify\fR [\fB\-\-vault\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Verify vault integrity without exporting secrets
.SH OPTIONS
.TP
\fB\-\-vault\fR \fI<VAULT>\fR [default: .murk]
Vault filename
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
