.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH diff 1  "diff " 
.SH NAME
diff \- Show secret changes vs a git ref
.SH SYNOPSIS
\fBmurk diff\fR [\fB\-\-show\-values\fR] [\fB\-\-json\fR] [\fB\-\-vault\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIGIT_REF\fR] 
.SH DESCRIPTION
Show secret changes vs a git ref
.SH OPTIONS
.TP
\fB\-\-show\-values\fR
Show actual values (not just key names)
.TP
\fB\-\-json\fR
Output as JSON
.TP
\fB\-\-vault\fR \fI<VAULT>\fR [default: .murk]
Vault filename
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIGIT_REF\fR] [default: HEAD]
Git ref to compare against
