.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH rm 1  "rm " 
.SH NAME
rm \- Remove a secret
.SH SYNOPSIS
\fBmurk rm\fR [\fB\-\-vault\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIKEY\fR> 
.SH DESCRIPTION
Remove a secret
.SH OPTIONS
.TP
\fB\-\-vault\fR \fI<VAULT>\fR [default: .murk]
Vault filename
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIKEY\fR>
Secret key name
