.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH revoke 1  "revoke " 
.SH NAME
revoke \- Revoke an agent grant and rotate the keys it could read
.SH SYNOPSIS
\fBmurk agent revoke\fR [\fB\-\-rotate\fR] [\fB\-\-vault\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Revoke an agent grant and rotate the keys it could read
.SH OPTIONS
.TP
\fB\-\-rotate\fR
Rotate the keys it could read in the same session
.TP
\fB\-\-vault\fR \fI<VAULT>\fR [default: .murk]
Vault filename
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Grant name
