.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH get 1  "get " 
.SH NAME
get \- Get a single decrypted value
.SH SYNOPSIS
\fBmurk get\fR [\fB\-\-vault\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIKEY\fR> 
.SH DESCRIPTION
Get a single decrypted value
.SH OPTIONS
.TP
\fB\-\-vault\fR \fI<VAULT>\fR [default: .murk]
Vault filename
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIKEY\fR>
Secret key name
