.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH clear 1  "clear " 
.SH NAME
clear \- Remove the policy — agent mode becomes unrestricted again
.SH SYNOPSIS
\fBmurk policy clear\fR [\fB\-\-vault\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Remove the policy — agent mode becomes unrestricted again
.SH OPTIONS
.TP
\fB\-\-vault\fR \fI<VAULT>\fR [default: .murk]
Vault filename
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
