.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH rm 1  "rm " 
.SH NAME
rm \- Remove a member from a group, or delete the group entirely
.SH SYNOPSIS
\fBmurk group rm\fR [\fB\-\-member\fR] [\fB\-\-vault\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Remove a member from a group, or delete the group entirely
.SH OPTIONS
.TP
\fB\-\-member\fR \fI<MEMBER>\fR
Recipient pubkey or display name to remove (omit to delete the group)
.TP
\fB\-\-vault\fR \fI<VAULT>\fR [default: .murk]
Vault filename
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Group name
