.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH group 1  "group " 
.SH NAME
group \- Manage recipient groups
.SH SYNOPSIS
\fBmurk group\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Manage recipient groups
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
group\-create(1)
Create a new recipient group (you become its first member)
.TP
group\-ls(1)
List groups and their members
.TP
group\-add(1)
Add a member to a group
.TP
group\-rm(1)
Remove a member from a group, or delete the group entirely
.TP
group\-help(1)
Print this message or the help of the given subcommand(s)
