.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH export 1  "export " 
.SH NAME
export \- Export all secrets as shell export statements
.SH SYNOPSIS
\fBmurk export\fR [\fB\-\-tag\fR] [\fB\-\-json\fR] [\fB\-\-vault\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Export all secrets as shell export statements
.SH OPTIONS
.TP
\fB\-\-tag\fR \fI<TAG>\fR
Filter by tag (repeatable)
.TP
\fB\-\-json\fR
Output as JSON
.TP
\fB\-\-vault\fR \fI<VAULT>\fR [default: .murk]
Vault filename
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
