.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH setup-merge-driver 1  "setup-merge-driver " 
.SH NAME
setup\-merge\-driver \- Configure git to use murk\*(Aqs merge driver for .murk files
.SH SYNOPSIS
\fBmurk setup\-merge\-driver\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Configure git to use murk\*(Aqs merge driver for .murk files
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
