.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH env 1  "env " 
.SH NAME
env \- Write a .envrc for direnv integration
.SH SYNOPSIS
\fBmurk env\fR [\fB\-\-vault\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Write a .envrc for direnv integration
.SH OPTIONS
.TP
\fB\-\-vault\fR \fI<VAULT>\fR [default: .murk]
Vault filename
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
