.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH circle 1  "circle " 
.SH NAME
circle \- Manage recipients
.SH SYNOPSIS
\fBmurk circle\fR [\fB\-\-json\fR] [\fB\-\-vault\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Manage recipients
.SH OPTIONS
.TP
\fB\-\-json\fR
Output as JSON
.TP
\fB\-\-vault\fR \fI<VAULT>\fR [default: .murk]
Vault filename
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
circle\-authorize(1)
Add a recipient to the vault
.TP
circle\-revoke(1)
Remove a recipient from the vault
.TP
circle\-help(1)
Print this message or the help of the given subcommand(s)
