.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH authorize 1  "authorize " 
.SH NAME
authorize \- Add a recipient to the vault
.SH SYNOPSIS
\fBmurk circle authorize\fR [\fB\-\-name\fR] [\fB\-\-group\fR] [\fB\-\-force\fR] [\fB\-\-allow\-ssh\-rsa\fR] [\fB\-\-vault\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPUBKEY\fR> 
.SH DESCRIPTION
Add a recipient to the vault
.SH OPTIONS
.TP
\fB\-\-name\fR \fI<NAME>\fR
Display name for this recipient
.TP
\fB\-\-group\fR \fI<GROUP>\fR
Also add the new recipient to this group
.TP
\fB\-\-force\fR
Accept changed GitHub keys without confirmation
.TP
\fB\-\-allow\-ssh\-rsa\fR
Allow ssh\-rsa recipients (rejected by default — use ed25519)
.TP
\fB\-\-vault\fR \fI<VAULT>\fR [default: .murk]
Vault filename
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPUBKEY\fR>
Public key (age1...), ssh:path, ssh: (default ~/.ssh/id_ed25519.pub), or github:username
