.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH edit 1  "edit " 
.SH NAME
edit \- Edit secrets in $EDITOR
.SH SYNOPSIS
\fBmurk edit\fR [\fB\-\-scoped\fR] [\fB\-\-group\fR] [\fB\-\-vault\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIKEY\fR] 
.SH DESCRIPTION
Edit secrets in $EDITOR
.SH OPTIONS
.TP
\fB\-\-scoped\fR
Edit scoped overrides instead of shared secrets
.TP
\fB\-\-group\fR \fI<GROUP>\fR
Edit values for this group instead of shared secrets
.TP
\fB\-\-vault\fR \fI<VAULT>\fR [default: .murk]
Vault filename
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIKEY\fR]
Edit a single key (omit to edit all)
